### ISSUE TITLE
'type' is not scriptable

### ISSUE THREAD

**Issue by arjunkc** [kosmospredanie/pdftowrite#3]
Using python3.7, when I run this I get

```
Traceback (most recent call last):
  File "/usr/local/bin/pdftowrite", line 5, in <module>
    from pdftowrite.pdftowrite import main
  File "/usr/local/lib/python3.7/site-packages/pdftowrite/pdftowrite.py", line 5, in <module>
    import pdftowrite.utils as utils
  File "/usr/local/lib/python3.7/site-packages/pdftowrite/utils.py", line 16, in <module>
    def apply_vars(text: str, vars: dict[str,Any]) -> str:
TypeError: 'type' object is not subscriptable
```

**Comment by michaelsjackson** [comment]
Same error here, ubuntu 18.04. Any solutions found? Thanks in advance.
